#ifndef PONG_CONFIG_H
#define PONG_CONFIG_H


/** GAME UI PARAMS */
#define PONG_PAD_WIDTH   (5U)
#define PONG_PAD_HEIGHT  (40U)
#define PONG_BALL_RADIUS (2U)
#define PONG_BALL_SPEED  (4U)

/** GAMEPLAY PARAMS  */
#define PONG_GAMEPLAY_POINTS_TO_WIN (5U)

#endif /* PONG_CONFIG_H */
